In [197]:
import cv2

import os

from glob import glob

anomalous_data_dir = os.path.join('.','assets',  'data', 'anomalous_dice', '*.jpg')
normal_data_dir = os.path.join('.','assets',  'data', 'normal_dice', '*')

anomalous_files = glob(anomalous_data_dir)
print(f"{len(anomalous_files)} anomalous files found")

normal_files_folders = glob(normal_data_dir)
normal_files_paths = []
labels = []
for folder in normal_files_folders:
    files = glob(folder + '\\*.jpg')
    normal_files_paths += files
    labels += [int(os.path.basename(folder))] * len(files)

print(f"{len(normal_files_paths)} normal files found")
print(f"{len(labels)} normal files labels found")
# for x in range(len(anomalous_files)):
#    print(anomalous_files[x])

img_size = 224
normal_images = []
threshold_im = []

82 anomalous files found
1077 normal files found
1077 normal files labels found

In [198]:
for img in normal_files_paths:
    try:
        img_arr = cv2.imread(img, cv2.IMREAD_GRAYSCALE)
        img_arr.shape
        resized_arr = cv2.resize(img_arr, (img_size, img_size))  # Reshaping images to preferred size
        _, thresh = cv2.threshold(resized_arr, 50, 255, cv2.THRESH_BINARY_INV)
        normal_images.append(resized_arr)
        threshold_im.append(thresh)
    except Exception as e:
        print(e)

In [199]:
import pandas as pd

df = pd.DataFrame(list(zip(labels, normal_images,threshold_im)),
               columns =['class', 'gray_arr', 'thresh'])

In [200]:
import numpy as np

df['mean_thresh'] = df['thresh'].apply(lambda x: np.mean(x))

In [201]:
df = df.groupby('class')['mean_thresh'].describe()

In [202]:
df.to_pickle('data/values_thresh_mask.pkl')

In [203]:
df[['mean','max']].iloc[0][0]

20.083811778655637

In [204]:
df

,count,mean,std,min,25%,50%,75%,max
class,,,,,,,,
0,103.0,20.083812,0.749935,17.873784,19.756706,20.226802,20.574926,21.243224
1,91.0,24.394244,0.812855,22.137675,23.888463,24.500857,25.009068,25.913684
2,63.0,35.415537,5.558306,19.174805,32.197714,35.488381,39.825963,45.403579
3,64.0,24.154003,0.692844,21.710778,23.572101,24.185766,24.640615,25.258092
4,120.0,32.118687,0.812452,29.847238,31.667904,32.124023,32.620800,34.045061
5,101.0,32.182443,0.836748,30.131836,31.605648,32.225666,32.779616,33.978994
6,178.0,40.226193,1.038041,37.414501,39.776412,40.377372,40.778858,48.025949
7,140.0,46.968942,1.048115,43.939931,46.131592,47.027314,47.792172,49.306641
8,72.0,32.343472,9.902070,11.023099,25.118333,34.459253,39.573128,48.645966
9,62.0,32.217633,6.323079,17.243603,27.970668,32.479771,37.857915,43.467295
10,83.0,32.055446,8.724727,13.594647,25.984833,33.094707,39.673499,45.545879